services:
  car-service:
    build: ./car-service
    container_name: car-service
    ports:
      - "8002:8002"
    volumes:
      - ./car-service:/app
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    volumes:
      - ./user-service:/app
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8003:8003"
    volumes:
      - ./order-service:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    environment:
      - CAR_SERVICE_URL=http://car-service:8002/graphql
      - USER_SERVICE_URL=http://user-service:8001/graphql
      - ORDER_SERVICE_URL=http://order-service:8003/graphql